import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Input } from '../components/Input'
import { BackButton } from '../components/BackButton'
import { FrequentlyAskedQuestion } from '../components/FAQ'
import { Button } from '../components/Button';
import { MdArrowForward } from 'react-icons/md';
import { Navbar } from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>

      <section className="flex bg-background">
        <Input labelName="Name" name='name' placeholder='Enter your name'/>

        <BackButton/>
        <FrequentlyAskedQuestion question='how old are you' answer='i am 15 yers old'/>
      </section>

      <Button endIcon={<MdArrowForward/>}>
        Explore the warehouse
      </Button>
    </main>
  )
}

export default Home
