import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Input } from '../components/Input'
import { BackButton } from '../components/BackButton'
import { FrequentlyAskedQuestion } from '../components/FAQ'
import { Button } from '../components/Button';
import { MdArrowForward } from 'react-icons/md';
import { Navbar } from '../components/Navbar'
import { SectionTitle } from '../components/SectionTitle'
import { Modal } from '../components/Modal'

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar currentPage='home'/>

      <section className="h-[100vh] md:h-full flex bg-background items-center flex-col-reverse justify-center md:flex-row relative px-2 md:px-4">
        <div className='w-56 md:w-1/3 h-56 md:h-[300px] bg-transparent border-primary border-4 opacity-30 z-0 absolute left-[-40%] md:left-[-20%] top-[20%] md:top-[5%]'/>
        <div className='w-56 md:w-1/3 h-60 md:h-[300px] bg-transparent border-primary border-4 opacity-30 z-0 absolute left-[1%] top-[48%] md:left-2 md:top-[34%]'/>
        <div className='flex items-start flex-col gap-2 z-10'>
          <h1 className='font-mono text-lg font-semibold md:text-4xl'>TANENA SERVICES NIGERIA</h1>
          <p className='text-md md:text-2xl'>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, quisquam vel
            aliquam harum eum non consectetur excepturi sit praesentium doloribus
            ratione quis assumenda quaerat natus iure nobis nesciunt placeat. Maxime!
          </p>

          <button className='flex items-center px-5 gap-2 my-2 font-semibold py-2 rounded-[30px] bg-primary text-white'>
            Get Started
            <MdArrowForward size={20}/>
          </button>
        </div>
        <img src="/images/hero-picture.svg" alt="drink" className='w-2/3 z-10 md:w-2/5 h:full'/>
      </section>


      <section className='relative'>
        <h2 className='font-semibold text-center text-lg mb-2'>
          OUR SERVICES
        </h2>
        <div className='w-full px-2 md-px-4 gap-5 flex flex-col justify-center md:flex-row md:gap-7'>

          <article className='background-tint text-zinc-900 p-0 border-[1.5px] rounded-sm w-full md:w-[400px]'>
            <img className='w-full' src='/images/drinks.svg' alt='our-warehouse'/>
            <div className='px-2 py-4 md:px-4'>
              <h3 className='font-medium font-sans text-lg'>Our Warehouse</h3>
              <p className="">
                Tanena Services Nigeria seeks to provide wholesale services to buyers 
                who need assorted drinks for any kind of event. sit praesentium doloribus
                ratione quis assumenda quaerat natus iure nobis nesciunt placeat
              </p>

              <button className='flex items-center px-5 gap-2 my-2 font-semibold py-2 rounded-[30px] bg-primary text-white'>
                Explore
                <MdArrowForward size={20}/>
              </button>
            </div>
          </article>

          <article className='background-tint text-zinc-900 p-0 border-[1.5px] rounded-sm w-full md:w-[400px]'>
            <img className='w-full' src='/images/cruizy-villa.svg' alt='our-warehouse'/>
            <div className='px-2 py-4 md:px-4'>
              <h3 className='font-medium font-sans text-lg'>Cruizy Villa</h3>
              <p>
                Tanena Services Nigeria seeks to provide wholesale services to buyers 
                who need assorted drinks for any kind of event. sit praesentium doloribus
                ratione quis assumenda quaerat natus iure nobis nesciunt placeat
              </p>

              <button className='flex items-center px-5 gap-2 mt-2 font-semibold py-2 rounded-[30px] bg-primary text-white'>
                Explore
                <MdArrowForward size={20}/>
              </button>
            </div>
          </article>

        </div>

        
      </section>

      <section className='md:grid md:grid-cols-2 flex flex-col'>
        <div className='md:w-full'>
          <h2 className='font-mono text-lg md:text-3xl'>OUR SERVICES</h2>
          <p className='text-md md:text-2xl'>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, quisquam vel
            aliquam harum eum non consectetur excepturi sit praesentium doloribus
            ratione quis assumenda quaerat natus iure nobis nesciunt placeat. Maxime!
          </p>

          <img src="/images/arrow.svg" alt='arrow'/>
        </div>

        <div className='rounded-2xl w-4/5 mx-auto h-full'>
          <ul className='m-0 px-4 list-none p-3 md:p-5 rounded-lg md:rounded-3xl bg-lightblue'>
            
            <li className='h-48 w-full grid grid-flow-col gap-2 bg-primary text-white rounded-xl md:rounded-[30px] p-2 md:p-4'>
              <span className='w-4 h-4 rounded-full bg-white'/>
              <div>
                <h3>Equipped Storage</h3>
                <p>
                  Paesentium doloribus
                  ratione quiassumendaraesentium doloribus
                  ratione quiassumenda raesentium doloribus ratio
                </p>
              </div>
            </li>

            

          </ul>
        </div>
      </section>

      <section className='flex justify-between w-full'>
        <img className='w-2/5' src="/images/delivery-illustration.svg" alt='fast delivery'/>
        <div>
          <h2>FAST DELIVERY ASSURED</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, quisquam vel
            aliquam harum eum non consectetur excepturi sit praesentium doloribus
            ratione quis assumenda quaerat natus iure nobis nesciunt placeat. Maxime!
          </p>
        </div>

      </section>

      <Modal isOpen={true}>
        hello
      </Modal>

    </main>
  )
}

export default Home
