import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Input } from '../components/Input'
import { BackButton } from '../components/BackButton'
import { FrequentlyAskedQuestion } from '../components/FAQ'
import { Button } from '../components/Button';
import { MdArrowForward } from 'react-icons/md';
import { Navbar } from '../components/Navbar'
import { SectionTitle } from '../components/SectionTitle'
import { Modal } from '../components/Modal'
import { Footer } from '../components/Footer'


const Services: NextPage = () => {
    return (
      <>

            <main>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Navbar currentPage='services' />

                <section className="h-[100vh] md:h-full flex bg-background items-center flex-col-reverse justify-center md:flex-row relative px-2 md:px-4">
        <div className='flex items-start flex-col gap-2 z-10'>
          <h1 className='font-mono text-lg font-semibold md:text-4xl'>TANENA SERVICES NIGERIA</h1>
          <p className='text-md md:text-2xl'>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Et, quisquam vel
            aliquam harum eum non consectetur excepturi sit praesentium doloribus
            ratione quis assumenda quaerat natus iure nobis nesciunt placeat. Maxime!
          </p>

         
        </div>
       
      </section>

            </main>

        </>
            )
}

            export default Services
